<section class="page-header"><div><p class="text-uppercase text-primary fw-bold small mb-1">Seguridad y privacidad</p><h1 class="fw-bold mb-1">Enrolar identidad facial</h1><p class="text-muted mb-0">Registra una referencia facial para validar posteriormente la identidad de un usuario.</p></div></section>
<?php if (!empty($message)): ?><div class="alert alert-success" role="status"><i class="bi bi-check-circle me-1" aria-hidden="true"></i><?= e($message) ?></div><?php endif; ?>
<?php if (!empty($error)): ?><div class="alert alert-danger" role="alert"><i class="bi bi-exclamation-triangle me-1" aria-hidden="true"></i><?= e($error) ?></div><?php endif; ?>
<?php if (empty($serviceSettings['enabled'])): ?><div class="alert alert-warning" role="status"><i class="bi bi-info-circle me-1" aria-hidden="true"></i>El servicio está desactivado. Configúralo en Administración → Reconocimiento facial antes de enrolar.</div><?php endif; ?>
<script>document.addEventListener('DOMContentLoaded',function(){var f=document.querySelector('[data-face-capture-form]');if(f){f.dataset.facePurpose='enroll';['face_challenge','face_start_key','face_embedding','face_liveness'].forEach(function(n){if(!f.querySelector('[name="'+n+'"]')){var i=document.createElement('input');i.type='hidden';i.name=n;i.value=n==='face_liveness'?'0':'';f.appendChild(i);}});}});</script>
<div class="card content-panel"><div class="card-body"><form method="post" enctype="multipart/form-data" class="row g-4" data-face-capture-form data-face-liveness-threshold="<?= e((string) ($serviceSettings['liveness_threshold'] ?? 0.60)) ?>"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="col-12 col-lg-5">
<?php if (!empty($isSelfEnrollment)): ?>
    <?php if ($selectedUser): ?><div class="rounded border bg-light-subtle p-3 mb-3" aria-label="Usuario de la sesión"><span class="form-label d-block mb-2">Usuario de la sesión</span><div class="fw-semibold"><?= e((string) ($selectedUser['name'] ?? '')) ?></div><div class="text-muted small">RUT: <?= e((string) ($selectedUser['rut'] ?? 'No registrado')) ?></div></div><?php else: ?><div class="alert alert-danger" role="alert">No se pudo cargar el usuario de la sesión.</div><?php endif; ?><input type="hidden" name="user_id" value="<?= (int) ($selfUserId ?? 0) ?>">
<?php else: ?>
    <label class="form-label" for="face_user_id">Usuario</label><select class="form-select form-select-lg js-face-user-select" id="face_user_id" name="user_id" data-placeholder="Selecciona un usuario" required><option value=""></option><?php foreach ($users as $user): ?><option value="<?= (int) $user['id'] ?>" <?= $selectedUser && (int) $selectedUser['id'] === (int) $user['id'] ? 'selected' : '' ?>><?= e($user['name']) ?><?= !empty($user['email']) ? ' · ' . e($user['email']) : '' ?></option><?php endforeach; ?></select>
<?php endif; ?>
<?php include __DIR__ . '/guidance.php'; ?></div><div class="col-12 col-lg-7"><div class="face-camera" data-face-camera><div class="face-camera-preview"><video data-face-video autoplay muted playsinline aria-label="Vista previa de la cámara"></video><div class="face-camera-placeholder" data-face-placeholder><i class="bi bi-camera-video" aria-hidden="true"></i><span>Activa la cámara para iniciar la prueba de vida</span></div><img data-face-photo class="d-none" alt="Fotografía facial capturada"></div><div class="face-camera-actions"><button type="button" class="btn btn-outline-primary" data-face-start><i class="bi bi-camera-video me-1"></i>Activar cámara</button><button type="button" class="btn btn-outline-secondary d-none" data-face-retake>Repetir</button></div><div class="face-camera-status" data-face-status role="status">La prueba de vida guiará la captura automáticamente.</div><label class="visually-hidden" for="face_image">Evidencia fotográfica generada por la cámara</label><input class="d-none" id="face_image" name="face_image" type="file" accept="image/jpeg,image/png,image/webp" aria-hidden="true" tabindex="-1"><p class="form-text">Una persona, rostro visible, mínimo 640×480. La imagen se adjunta automáticamente al completar la prueba de vida.</p></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" id="face_consent" name="consent" value="1" type="checkbox" required><label class="form-check-label" for="face_consent">Confirmo que existe consentimiento explícito para registrar esta referencia facial y utilizarla únicamente para verificación de identidad.</label></div></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary" type="submit" <?= empty($serviceSettings['enabled']) ? 'disabled' : '' ?>><i class="bi bi-person-plus me-1"></i><?= !empty($isSelfEnrollment) ? 'Enrolar mi identidad' : 'Enrolar usuario' ?></button><a class="btn btn-outline-secondary" href="<?= e(route_url('dashboard')) ?>">Cancelar</a></div></form></div></div>
