<section class="page-header"<?= !empty($assessmentEntry) ? ' data-page-back-url="' . e(route_url('my-tests')) . '"' : '' ?>>
    <div>
        <p class="text-uppercase text-primary fw-bold small mb-1">Seguridad y privacidad</p>
        <h1 class="fw-bold mb-1"><?= !empty($assessmentEntry) ? 'Verificar identidad' : 'Validar identidad' ?></h1>
        <p class="text-muted mb-0"><?= !empty($assessmentEntry) ? 'Antes de continuar, confirma tu identidad con la cámara.' : 'Compara una captura actual contra la referencia facial enrolada del usuario.' ?></p>
    </div>
</section>
<?php if (!empty($error)): ?><div class="alert alert-warning" role="alert"><i class="bi bi-exclamation-triangle me-1" aria-hidden="true"></i><?= e($error) ?><?php if (!empty($assessmentEntry) && (strpos((string) $error, 'enrolar') !== false || strpos((string) $error, 'nuevo enrolamiento') !== false)): ?> <a href="<?= e(route_url('facial-recognition.enroll')) ?>">Enrolar identidad</a><?php endif; ?></div><?php endif; ?>
<?php if (empty($serviceSettings['enabled'])): ?><div class="alert alert-warning" role="status"><i class="bi bi-info-circle me-1" aria-hidden="true"></i>El servicio de reconocimiento facial está desactivado. Contacta al administrador.</div><?php endif; ?>
<script>document.addEventListener('DOMContentLoaded',function(){var f=document.querySelector('[data-face-capture-form]');if(f){f.dataset.facePurpose='<?= !empty($assessmentEntry) ? 'assessment_entry' : 'validate' ?>';['face_challenge','face_start_key','face_embedding','face_liveness'].forEach(function(n){if(!f.querySelector('[name="'+n+'"]')){var i=document.createElement('input');i.type='hidden';i.name=n;i.value=n==='face_liveness'?'0':'';f.appendChild(i);}});}});</script>
<div class="card content-panel"><div class="card-body">
    <?php if (!empty($assessmentEntry)): ?><?php $assessmentStep = 1; $assessmentComponentsRequired = true; include dirname(__DIR__) . '/partials/assessment_stepper.php'; ?><div class="mb-3"><h2 class="h5 mb-1">Paso 1: validación facial</h2><p class="text-muted mb-0">Al aprobar, continuarás a la autorización de componentes y al consentimiento audiovisual de esta actividad.</p></div><?php endif; ?>
    <form method="post" enctype="multipart/form-data" class="row g-4" data-face-capture-form data-face-liveness-threshold="<?= e((string) ($serviceSettings['liveness_threshold'] ?? 0.60)) ?>">
        <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
        <?php if (!empty($assessmentEntry)): ?>
            <input type="hidden" name="user_id" value="<?= (int) ($assessmentUser['id'] ?? 0) ?>">
            <input type="hidden" name="return_to" value="<?= e($assessmentReturnTo) ?>">
        <?php else: ?>
            <div class="col-12 col-lg-5"><label class="form-label" for="face_validate_user_id">Usuario enrolado</label><select class="form-select form-select-lg js-face-user-select" id="face_validate_user_id" name="user_id" data-placeholder="Selecciona un usuario" required><option value=""></option><?php foreach ($users as $user): ?><option value="<?= (int) $user['id'] ?>"><?= e($user['name']) ?><?= !empty($user['email']) ? ' · ' . e($user['email']) : '' ?></option><?php endforeach; ?></select><?php include __DIR__ . '/guidance.php'; ?></div>
        <?php endif; ?>
        <div class="col-12 col-lg-7"><div class="face-camera" data-face-camera><div class="face-camera-preview"><video data-face-video autoplay muted playsinline aria-label="Vista previa de la cámara"></video><div class="face-camera-placeholder" data-face-placeholder><i class="bi bi-camera-video" aria-hidden="true"></i><span>Activa la cámara para iniciar la prueba de vida</span></div><img data-face-photo class="d-none" alt="Fotografía facial capturada"></div><div class="face-camera-actions"><button type="button" class="btn btn-outline-primary" data-face-start><i class="bi bi-camera-video me-1"></i>Activar cámara</button><button type="button" class="btn btn-outline-secondary d-none" data-face-retake>Repetir</button></div><div class="face-camera-status" data-face-status role="status">La prueba de vida guiará la captura automáticamente.</div><label class="visually-hidden" for="face_validate_image">Imagen temporal generada por la cámara</label><input class="d-none" id="face_validate_image" name="face_image" type="file" accept="image/jpeg,image/png,image/webp" aria-hidden="true" tabindex="-1"><p class="form-text">La captura se procesa temporalmente y no se conserva como evidencia.</p></div></div>
        <div class="col-12 d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit" <?= empty($serviceSettings['enabled']) || (!empty($assessmentEntry) && (!$enrollment || ($enrollment['status'] ?? '') !== 'active')) ? 'disabled' : '' ?>><i class="bi bi-person-check me-1"></i><?= !empty($assessmentEntry) ? 'Verificar y continuar' : 'Validar identidad' ?></button><a class="btn btn-outline-secondary" href="<?= e(!empty($assessmentEntry) ? route_url('my-tests') : route_url('dashboard')) ?>">Cancelar</a></div>
    </form>
</div></div>
