-- Preconfiguración inicial de identidad visual e-talent.
-- Estos valores viven en platform_settings y son editables desde Administración > Identidad visual.
USE e_talent_core;
SET NAMES utf8mb4;

INSERT IGNORE INTO platform_settings (setting_key, setting_value) VALUES
('login_title', 'e-talent'),
('login_title_font_size', '40'),
('login_subtitle', 'Evalúa el talento. Decide con evidencia.'),
('login_subtitle_font_size', '16'),
('login_form_position', 'right'),
('login_background_color', '#F7F9FC'),
('login_form_background_color', '#FFFFFF'),
('login_title_color', '#2146D0'),
('login_subtitle_color', '#475569'),
('login_button_color', '#2146D0'),
('login_logo_path', 'assets/img/branding/et-propuesta-c/logo.svg'),
('login_background_path', 'assets/img/branding/et-propuesta-c/login-background.png'),
('app_font_url', 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap'),
('app_font_family', 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'),
('font_heading_family', 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'),
('font_body_family', 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'),
('app_font_size', '16'),
('font_size_h1', '40'),
('font_size_h2', '24'),
('font_size_h3', '20'),
('font_size_subtitle', '18'),
('font_size_body', '16'),
('font_size_small', '13'),
('font_size_nav', '15'),
('font_size_button', '16'),
('font_size_table', '14'),
('app_primary_color', '#2146D0'),
('portal_text_color', '#172554'),
('html_favicon_path', 'assets/img/branding/et-propuesta-c/favicon.svg'),
('topbar_icon_path', 'assets/img/branding/et-propuesta-c/logo-white.svg'),
('topbar_name', 'e-talent'),
('topbar_background_color', '#2146D0'),
('topbar_menu_background_color', '#2146D0'),
('topbar_menu_button_color', '#36C7B4'),
('topbar_height', '72'),
('topbar_logo_width', '42'),
('sidebar_background_color', '#FFFFFF'),
('sidebar_text_color', '#344054'),
('sidebar_icon_color', '#98A2B3'),
('sidebar_active_background_color', '#EEF2FF'),
('sidebar_active_text_color', '#2146D0'),
('sidebar_border_color', '#E4E7EC'),
('sidebar_width', '280'),
('layout_background_color', '#F7F9FC'),
('card_header_background_color', '#EEF2FF'),
('card_content_background_color', '#FFFFFF'),
('card_text_color', '#172554'),
('button_background_color', '#2146D0'),
('button_text_color', '#FFFFFF'),
('table_border_color', '#D8E0F0'),
('table_header_background_color', '#EEF2FF'),
('table_header_text_color', '#172554'),
('table_body_background_color', '#FFFFFF'),
('table_body_text_color', '#172554');
