<?php
$assignments = is_array($assignments ?? null) ? $assignments : [];
$user = is_array($user ?? null) ? $user : null;
$labels = ['assigned' => 'Pendiente', 'in_progress' => 'En curso', 'completed' => 'Completada', 'expired' => 'Expirada', 'cancelled' => 'Cancelada'];
$selectedAnswers = is_array($selectedAnswers ?? null) ? $selectedAnswers : [];
?>
<section class="page-header"><div><p class="dashboard-kicker mb-1">Avance</p><h1 class="fw-bold mb-1">Consultar Usuario</h1><p class="text-muted mb-0">Consulta los procesos vinculados, el estado de cada evaluación y test y las respuestas guardadas.</p></div></section>
<section class="card content-panel mb-4"><form class="row g-3 align-items-end" method="get" action="<?= e(route_url('client-admin.user-lookup')) ?>"><div class="col-12 col-md-5"><label class="form-label" for="client-user-rut">RUT usuario</label><input class="form-control" id="client-user-rut" name="rut" value="<?= e((string) ($rut ?? '')) ?>" maxlength="12" placeholder="12.345.678-5" required></div><div class="col-auto"><button class="btn btn-primary" type="submit"><i class="bi bi-search me-1"></i>Consultar</button></div></form>
    <?php if (!empty($error)): ?><div class="alert alert-warning mt-3 mb-0"><?= e((string) $error) ?></div><?php elseif (($rut ?? '') !== '' && !$user): ?><div class="alert alert-info mt-3 mb-0">No se encontró un usuario de tu empresa con ese RUT.</div><?php endif; ?>
</section>
<?php if ($user): ?>
<section class="card content-panel mb-4"><h2 class="h5 fw-bold mb-1"><?= e((string) ($user['name'] ?? 'Usuario')) ?></h2><div class="text-muted"><?= e((string) ($user['rut'] ?? '')) ?><?= !empty($user['email']) ? ' · ' . e((string) $user['email']) : '' ?></div></section>
<?= status_help_button('Estados de la actividad', "• Pendiente: asignada y aún no abierta.\n• En curso: intento abierto, que puede no tener respuestas.\n• Completada: entrega explícita, incluso vacía.\n• Expirada: venció sin envío y no equivale a completada.\n• Cancelada: se retiró del flujo. Las respuestas guardadas son independientes del estado.") ?>
<?php if (!$assignments): ?><section class="card content-panel"><div class="alert alert-light border mb-0">Este usuario no tiene evaluaciones o tests vinculados a procesos.</div></section><?php else: foreach ($assignments as $assignment): ?>
<section class="card content-panel mb-3"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h2 class="h5 fw-bold mb-1"><?= e((string) ($assignment['process_name'] ?? 'Proceso')) ?></h2><span class="small text-muted"><?= e((string) ($assignment['process_code'] ?? '')) ?></span></div><span class="badge text-bg-light border"><?= e((string) ($assignment['activity_type'] ?? '') === 'test' ? 'Test psicolaboral' : 'Evaluación') ?> · <?= e($labels[(string) ($assignment['status'] ?? '')] ?? labelize((string) ($assignment['status'] ?? ''))) ?></span></div>
    <h3 class="h6 fw-bold"><?= e((string) ($assignment['activity_name'] ?? 'Actividad')) ?></h3>
    <?php if (!empty($assignment['record_id'])): ?><a class="btn btn-sm btn-outline-primary" aria-label="Ver respuestas de <?= e((string) ($assignment['activity_name'] ?? 'actividad')) ?>" href="<?= e(route_url('client-admin.user-lookup') . '?' . http_build_query(['rut' => $rut, 'activity_id' => (int) $assignment['record_id'], 'activity_type' => (string) $assignment['activity_type']])) ?>"><i class="bi bi-eye me-1"></i>Ver respuestas</a><?php else: ?><p class="text-muted mb-0">La persona aún no ha iniciado esta actividad.</p><?php endif; ?>
</section>
<?php endforeach; endif; ?><?php endif; ?>
<?php if ($selectedActivityName !== '' && $user): ?><section class="card content-panel"><h2 class="h5 fw-bold mb-3">Respuestas de <?= e($selectedActivityName) ?> · <?= e($selectedActivityType === 'test' ? 'Test psicolaboral' : 'Evaluación') ?></h2><?php if (!$selectedAnswers): ?><p class="text-muted mb-0">No hay respuestas guardadas para esta actividad.</p><?php else: ?><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Pregunta</th><th>Respuesta seleccionada</th></tr></thead><tbody><?php foreach ($selectedAnswers as $answer): ?><tr><td><?= e((string) ($answer['prompt'] ?? $answer['item_key'] ?? 'Pregunta')) ?></td><td><?= nl2br(e((string) ($answer['answer_value'] ?? ''))) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><?php endif; ?>
